refactor(Makefile): Cleanup variables
nextcloud/appstore pull request #1367
Opened 2024-04-29 07:37 UTC by provokateurin

Trying to understand the Makefile with all these unnecessary variables is really hard, so I just removed them and moved almost everything inline.

2024-06-09 15:47 UTC, joshtrichards approved these changes
Made one small additional adjustment that was needed. Passes all tests now.

2024-06-09 22:35 UTC, provokateurin commented
Maybe @bigcat88 you can review this as well?

2024-06-10 05:01 UTC, bigcat88 commented
> Made one small additional adjustment that was needed. Passes all tests now.

Thank you again


> Maybe @bigcat88 you can review this as well?

Looks good, let's merge this

2024-06-10 05:01 UTC, bigcat88 approved these changes

2024-06-10 05:06 UTC, bigcat88 requested changes

2024-06-10 05:06 UTC, bigcat88 commented on Makefile
> -db=sqlite
please return "$db" variable

2024-06-10 14:26 UTC, bigcat88 approved these changes
now the tests for `pgsql` is run on `pgsql` and not on `sqlite`

2024-06-10 14:26 UTC, merged